library(shiny)

shinyUI(fluidPage(
    
    titlePanel("Staff Scheduling"),
    h6('Created by Thomas Roh'),
    br(),
        sidebarLayout(
#             tabsetPanel(
#                 
#                 tabPanel("Scheduler",
            
                sidebarPanel(
                    fluidRow(
                        column(4,
                               selectInput("weekday1",label = NULL,choices = list("Sunday" = 1, "Monday" = 2, "Tuesday" = 3,
                                                                                  "Wednesday" = 4, "Thursday" = 5, "Friday" = 6,
                                                                                  "Saturday" = 7),selected = 1)),
                        column(4,
                               selectInput("hour1",label = NULL,choices = list("0:00" = 1, "1:00" = 2, "2:00" = 3, "3:00" = 4,
                                                                               "4:00" = 5, "5:00" = 6, "6:00" = 7, "7:00" = 8,
                                                                               "8:00" = 9, "9:00" = 10, "10:00" = 11, "11:00" = 12,
                                                                               "12:00" = 13, "13:00" = 14, "14:00" = 15, "15:00" = 16,
                                                                               "16:00" = 17, "17:00" = 18, "18:00" = 19, "19:00" = 20,
                                                                               "20:00" = 21, "21:00" = 22, "22:00" = 23, "23:00" = 24),
                                           selected = 1)),
                        column(4,
                               numericInput("shift1",label = NULL,value = 0))),
                    fluidRow(
                        column(4,
                               selectInput("weekday2",label = NULL,choices = list("Sunday" = 1, "Monday" = 2, "Tuesday" = 3,
                                                                                  "Wednesday" = 4, "Thursday" = 5, "Friday" = 6,
                                                                                  "Saturday" = 7),selected = 1)),
                        column(4,
                               selectInput("hour2",label = NULL,choices = list("0:00" = 1, "1:00" = 2, "2:00" = 3, "3:00" = 4,
                                                                               "4:00" = 5, "5:00" = 6, "6:00" = 7, "7:00" = 8,
                                                                               "8:00" = 9, "9:00" = 10, "10:00" = 11, "11:00" = 12,
                                                                               "12:00" = 13, "13:00" = 14, "14:00" = 15, "15:00" = 16,
                                                                               "16:00" = 17, "17:00" = 18, "18:00" = 19, "19:00" = 20,
                                                                               "20:00" = 21, "21:00" = 22, "22:00" = 23, "23:00" = 24),
                                           selected = 1)),
                        column(4,
                               numericInput("shift2",label = NULL,value = 0))),
                    fluidRow(
                        column(4,
                               selectInput("weekday3",label = NULL,choices = list("Sunday" = 1, "Monday" = 2, "Tuesday" = 3,
                                                                                  "Wednesday" = 4, "Thursday" = 5, "Friday" = 6,
                                                                                  "Saturday" = 7),selected = 1)),
                        column(4,
                               selectInput("hour3",label = NULL,choices = list("0:00" = 1, "1:00" = 2, "2:00" = 3, "3:00" = 4,
                                                                               "4:00" = 5, "5:00" = 6, "6:00" = 7, "7:00" = 8,
                                                                               "8:00" = 9, "9:00" = 10, "10:00" = 11, "11:00" = 12,
                                                                               "12:00" = 13, "13:00" = 14, "14:00" = 15, "15:00" = 16,
                                                                               "16:00" = 17, "17:00" = 18, "18:00" = 19, "19:00" = 20,
                                                                               "20:00" = 21, "21:00" = 22, "22:00" = 23, "23:00" = 24),
                                           selected = 1)),
                        column(4,
                               numericInput("shift3",label = NULL,value = 0))),
                    fluidRow(
                        column(4,
                               selectInput("weekday4",label = NULL,choices = list("Sunday" = 1, "Monday" = 2, "Tuesday" = 3,
                                                                                  "Wednesday" = 4, "Thursday" = 5, "Friday" = 6,
                                                                                  "Saturday" = 7),selected = 1)),
                        column(4,
                               selectInput("hour4",label = NULL,choices = list("0:00" = 1, "1:00" = 2, "2:00" = 3, "3:00" = 4,
                                                                               "4:00" = 5, "5:00" = 6, "6:00" = 7, "7:00" = 8,
                                                                               "8:00" = 9, "9:00" = 10, "10:00" = 11, "11:00" = 12,
                                                                               "12:00" = 13, "13:00" = 14, "14:00" = 15, "15:00" = 16,
                                                                               "16:00" = 17, "17:00" = 18, "18:00" = 19, "19:00" = 20,
                                                                               "20:00" = 21, "21:00" = 22, "22:00" = 23, "23:00" = 24),
                                           selected = 1)),
                        column(4,
                               numericInput("shift4",label = NULL,value = 0))),
                    fluidRow(
                        column(4,
                               selectInput("weekday5",label = NULL,choices = list("Sunday" = 1, "Monday" = 2, "Tuesday" = 3,
                                                                                  "Wednesday" = 4, "Thursday" = 5, "Friday" = 6,
                                                                                  "Saturday" = 7),selected = 1)),
                        column(4,
                               selectInput("hour5",label = NULL,choices = list("0:00" = 1, "1:00" = 2, "2:00" = 3, "3:00" = 4,
                                                                               "4:00" = 5, "5:00" = 6, "6:00" = 7, "7:00" = 8,
                                                                               "8:00" = 9, "9:00" = 10, "10:00" = 11, "11:00" = 12,
                                                                               "12:00" = 13, "13:00" = 14, "14:00" = 15, "15:00" = 16,
                                                                               "16:00" = 17, "17:00" = 18, "18:00" = 19, "19:00" = 20,
                                                                               "20:00" = 21, "21:00" = 22, "22:00" = 23, "23:00" = 24),
                                           selected = 1)),
                        column(4,
                               numericInput("shift5",label = NULL,value = 0))),
                    fluidRow(
                        column(4,
                               selectInput("weekday6",label = NULL,choices = list("Sunday" = 1, "Monday" = 2, "Tuesday" = 3,
                                                                                  "Wednesday" = 4, "Thursday" = 5, "Friday" = 6,
                                                                                  "Saturday" = 7),selected = 1)),
                        column(4,
                               selectInput("hour6",label = NULL,choices = list("0:00" = 1, "1:00" = 2, "2:00" = 3, "3:00" = 4,
                                                                               "4:00" = 5, "5:00" = 6, "6:00" = 7, "7:00" = 8,
                                                                               "8:00" = 9, "9:00" = 10, "10:00" = 11, "11:00" = 12,
                                                                               "12:00" = 13, "13:00" = 14, "14:00" = 15, "15:00" = 16,
                                                                               "16:00" = 17, "17:00" = 18, "18:00" = 19, "19:00" = 20,
                                                                               "20:00" = 21, "21:00" = 22, "22:00" = 23, "23:00" = 24),
                                           selected = 1)),
                        column(4,
                               numericInput("shift6",label = NULL,value = 0))),
                    fluidRow(
                        column(4,
                               selectInput("weekday7",label = NULL,choices = list("Sunday" = 1, "Monday" = 2, "Tuesday" = 3,
                                                                                  "Wednesday" = 4, "Thursday" = 5, "Friday" = 6,
                                                                                  "Saturday" = 7),selected = 1)),
                        column(4,
                               selectInput("hour7",label = NULL,choices = list("0:00" = 1, "1:00" = 2, "2:00" = 3, "3:00" = 4,
                                                                               "4:00" = 5, "5:00" = 6, "6:00" = 7, "7:00" = 8,
                                                                               "8:00" = 9, "9:00" = 10, "10:00" = 11, "11:00" = 12,
                                                                               "12:00" = 13, "13:00" = 14, "14:00" = 15, "15:00" = 16,
                                                                               "16:00" = 17, "17:00" = 18, "18:00" = 19, "19:00" = 20,
                                                                               "20:00" = 21, "21:00" = 22, "22:00" = 23, "23:00" = 24),
                                           selected = 1)),
                        column(4,
                               numericInput("shift7",label = NULL,value = 0))),
                    fluidRow(
                        column(4,
                               selectInput("weekday8",label = NULL,choices = list("Sunday" = 1, "Monday" = 2, "Tuesday" = 3,
                                                                                  "Wednesday" = 4, "Thursday" = 5, "Friday" = 6,
                                                                                  "Saturday" = 7),selected = 1)),
                        column(4,
                               selectInput("hour8",label = NULL,choices = list("0:00" = 1, "1:00" = 2, "2:00" = 3, "3:00" = 4,
                                                                               "4:00" = 5, "5:00" = 6, "6:00" = 7, "7:00" = 8,
                                                                               "8:00" = 9, "9:00" = 10, "10:00" = 11, "11:00" = 12,
                                                                               "12:00" = 13, "13:00" = 14, "14:00" = 15, "15:00" = 16,
                                                                               "16:00" = 17, "17:00" = 18, "18:00" = 19, "19:00" = 20,
                                                                               "20:00" = 21, "21:00" = 22, "22:00" = 23, "23:00" = 24),
                                           selected = 1)),
                        column(4,
                               numericInput("shift8",label = NULL,value = 0))),
                    fluidRow(
                        column(4,
                               selectInput("weekday9",label = NULL,choices = list("Sunday" = 1, "Monday" = 2, "Tuesday" = 3,
                                                                                  "Wednesday" = 4, "Thursday" = 5, "Friday" = 6,
                                                                                  "Saturday" = 7),selected = 1)),
                        column(4,
                               selectInput("hour9",label = NULL,choices = list("0:00" = 1, "1:00" = 2, "2:00" = 3, "3:00" = 4,
                                                                               "4:00" = 5, "5:00" = 6, "6:00" = 7, "7:00" = 8,
                                                                               "8:00" = 9, "9:00" = 10, "10:00" = 11, "11:00" = 12,
                                                                               "12:00" = 13, "13:00" = 14, "14:00" = 15, "15:00" = 16,
                                                                               "16:00" = 17, "17:00" = 18, "18:00" = 19, "19:00" = 20,
                                                                               "20:00" = 21, "21:00" = 22, "22:00" = 23, "23:00" = 24),
                                           selected = 1)),
                        column(4,
                               numericInput("shift9",label = NULL,value = 0))),
                    fluidRow(
                        column(4,
                               selectInput("weekday10",label = NULL,choices = list("Sunday" = 1, "Monday" = 2, "Tuesday" = 3,
                                                                                   "Wednesday" = 4, "Thursday" = 5, "Friday" = 6,
                                                                                   "Saturday" = 7),selected = 1)),
                        column(4,
                               selectInput("hour10",label = NULL,choices = list("0:00" = 1, "1:00" = 2, "2:00" = 3, "3:00" = 4,
                                                                                "4:00" = 5, "5:00" = 6, "6:00" = 7, "7:00" = 8,
                                                                                "8:00" = 9, "9:00" = 10, "10:00" = 11, "11:00" = 12,
                                                                                "12:00" = 13, "13:00" = 14, "14:00" = 15, "15:00" = 16,
                                                                                "16:00" = 17, "17:00" = 18, "18:00" = 19, "19:00" = 20,
                                                                                "20:00" = 21, "21:00" = 22, "22:00" = 23, "23:00" = 24),
                                           selected = 1)),
                        column(4,
                               numericInput("shift10",label = NULL,value = 0))),
                    fluidRow(
                        column(4,
                               selectInput("weekday11",label = NULL,choices = list("Sunday" = 1, "Monday" = 2, "Tuesday" = 3,
                                                                                   "Wednesday" = 4, "Thursday" = 5, "Friday" = 6,
                                                                                   "Saturday" = 7),selected = 1)),
                        column(4,
                               selectInput("hour11",label = NULL,choices = list("0:00" = 1, "1:00" = 2, "2:00" = 3, "3:00" = 4,
                                                                                "4:00" = 5, "5:00" = 6, "6:00" = 7, "7:00" = 8,
                                                                                "8:00" = 9, "9:00" = 10, "10:00" = 11, "11:00" = 12,
                                                                                "12:00" = 13, "13:00" = 14, "14:00" = 15, "15:00" = 16,
                                                                                "16:00" = 17, "17:00" = 18, "18:00" = 19, "19:00" = 20,
                                                                                "20:00" = 21, "21:00" = 22, "22:00" = 23, "23:00" = 24),
                                           selected = 1)),
                        column(4,
                               numericInput("shift11",label = NULL,value = 0))),
                    fluidRow(
                        column(4,
                               selectInput("weekday12",label = NULL,choices = list("Sunday" = 1, "Monday" = 2, "Tuesday" = 3,
                                                                                   "Wednesday" = 4, "Thursday" = 5, "Friday" = 6,
                                                                                   "Saturday" = 7),selected = 1)),
                        column(4,
                               selectInput("hour12",label = NULL,choices = list("0:00" = 1, "1:00" = 2, "2:00" = 3, "3:00" = 4,
                                                                                "4:00" = 5, "5:00" = 6, "6:00" = 7, "7:00" = 8,
                                                                                "8:00" = 9, "9:00" = 10, "10:00" = 11, "11:00" = 12,
                                                                                "12:00" = 13, "13:00" = 14, "14:00" = 15, "15:00" = 16,
                                                                                "16:00" = 17, "17:00" = 18, "18:00" = 19, "19:00" = 20,
                                                                                "20:00" = 21, "21:00" = 22, "22:00" = 23, "23:00" = 24),
                                           selected = 1)),
                        column(4,
                               numericInput("shift12",label = NULL,value = 0))),
                    fluidRow(
                        column(4,
                               selectInput("weekday13",label = NULL,choices = list("Sunday" = 1, "Monday" = 2, "Tuesday" = 3,
                                                                                   "Wednesday" = 4, "Thursday" = 5, "Friday" = 6,
                                                                                   "Saturday" = 7),selected = 1)),
                        column(4,
                               selectInput("hour13",label = NULL,choices = list("0:00" = 1, "1:00" = 2, "2:00" = 3, "3:00" = 4,
                                                                                "4:00" = 5, "5:00" = 6, "6:00" = 7, "7:00" = 8,
                                                                                "8:00" = 9, "9:00" = 10, "10:00" = 11, "11:00" = 12,
                                                                                "12:00" = 13, "13:00" = 14, "14:00" = 15, "15:00" = 16,
                                                                                "16:00" = 17, "17:00" = 18, "18:00" = 19, "19:00" = 20,
                                                                                "20:00" = 21, "21:00" = 22, "22:00" = 23, "23:00" = 24),
                                           selected = 1)),
                        column(4,
                               numericInput("shift13",label = NULL,value = 0))),
                    fluidRow(
                        column(4,
                               selectInput("weekday14",label = NULL,choices = list("Sunday" = 1, "Monday" = 2, "Tuesday" = 3,
                                                                                   "Wednesday" = 4, "Thursday" = 5, "Friday" = 6,
                                                                                   "Saturday" = 7),selected = 1)),
                        column(4,
                               selectInput("hour14",label = NULL,choices = list("0:00" = 1, "1:00" = 2, "2:00" = 3, "3:00" = 4,
                                                                                "4:00" = 5, "5:00" = 6, "6:00" = 7, "7:00" = 8,
                                                                                "8:00" = 9, "9:00" = 10, "10:00" = 11, "11:00" = 12,
                                                                                "12:00" = 13, "13:00" = 14, "14:00" = 15, "15:00" = 16,
                                                                                "16:00" = 17, "17:00" = 18, "18:00" = 19, "19:00" = 20,
                                                                                "20:00" = 21, "21:00" = 22, "22:00" = 23, "23:00" = 24),
                                           selected = 1)),
                        column(4,
                               numericInput("shift14",label = NULL,value = 0))),
                    fluidRow(
                        column(4,
                               selectInput("weekday15",label = NULL,choices = list("Sunday" = 1, "Monday" = 2, "Tuesday" = 3,
                                                                                   "Wednesday" = 4, "Thursday" = 5, "Friday" = 6,
                                                                                   "Saturday" = 7),selected = 1)),
                        column(4,
                               selectInput("hour15",label = NULL,choices = list("0:00" = 1, "1:00" = 2, "2:00" = 3, "3:00" = 4,
                                                                                "4:00" = 5, "5:00" = 6, "6:00" = 7, "7:00" = 8,
                                                                                "8:00" = 9, "9:00" = 10, "10:00" = 11, "11:00" = 12,
                                                                                "12:00" = 13, "13:00" = 14, "14:00" = 15, "15:00" = 16,
                                                                                "16:00" = 17, "17:00" = 18, "18:00" = 19, "19:00" = 20,
                                                                                "20:00" = 21, "21:00" = 22, "22:00" = 23, "23:00" = 24),
                                           selected = 1)),
                        column(4,
                               numericInput("shift15",label = NULL,value = 0))),
                    fluidRow(
                        column(4,
                               selectInput("weekday16",label = NULL,choices = list("Sunday" = 1, "Monday" = 2, "Tuesday" = 3,
                                                                                   "Wednesday" = 4, "Thursday" = 5, "Friday" = 6,
                                                                                   "Saturday" = 7),selected = 1)),
                        column(4,
                               selectInput("hour16",label = NULL,choices = list("0:00" = 1, "1:00" = 2, "2:00" = 3, "3:00" = 4,
                                                                                "4:00" = 5, "5:00" = 6, "6:00" = 7, "7:00" = 8,
                                                                                "8:00" = 9, "9:00" = 10, "10:00" = 11, "11:00" = 12,
                                                                                "12:00" = 13, "13:00" = 14, "14:00" = 15, "15:00" = 16,
                                                                                "16:00" = 17, "17:00" = 18, "18:00" = 19, "19:00" = 20,
                                                                                "20:00" = 21, "21:00" = 22, "22:00" = 23, "23:00" = 24),
                                           selected = 1)),
                        column(4,
                               numericInput("shift16",label = NULL,value = 0))),
                    fluidRow(
                        column(4,
                               selectInput("weekday17",label = NULL,choices = list("Sunday" = 1, "Monday" = 2, "Tuesday" = 3,
                                                                                   "Wednesday" = 4, "Thursday" = 5, "Friday" = 6,
                                                                                   "Saturday" = 7),selected = 1)),
                        column(4,
                               selectInput("hour17",label = NULL,choices = list("0:00" = 1, "1:00" = 2, "2:00" = 3, "3:00" = 4,
                                                                                "4:00" = 5, "5:00" = 6, "6:00" = 7, "7:00" = 8,
                                                                                "8:00" = 9, "9:00" = 10, "10:00" = 11, "11:00" = 12,
                                                                                "12:00" = 13, "13:00" = 14, "14:00" = 15, "15:00" = 16,
                                                                                "16:00" = 17, "17:00" = 18, "18:00" = 19, "19:00" = 20,
                                                                                "20:00" = 21, "21:00" = 22, "22:00" = 23, "23:00" = 24),
                                           selected = 1)),
                        column(4,
                               numericInput("shift17",label = NULL,value = 0))),
                    fluidRow(
                        column(4,
                               selectInput("weekday18",label = NULL,choices = list("Sunday" = 1, "Monday" = 2, "Tuesday" = 3,
                                                                                   "Wednesday" = 4, "Thursday" = 5, "Friday" = 6,
                                                                                   "Saturday" = 7),selected = 1)),
                        column(4,
                               selectInput("hour18",label = NULL,choices = list("0:00" = 1, "1:00" = 2, "2:00" = 3, "3:00" = 4,
                                                                                "4:00" = 5, "5:00" = 6, "6:00" = 7, "7:00" = 8,
                                                                                "8:00" = 9, "9:00" = 10, "10:00" = 11, "11:00" = 12,
                                                                                "12:00" = 13, "13:00" = 14, "14:00" = 15, "15:00" = 16,
                                                                                "16:00" = 17, "17:00" = 18, "18:00" = 19, "19:00" = 20,
                                                                                "20:00" = 21, "21:00" = 22, "22:00" = 23, "23:00" = 24),
                                           selected = 1)),
                        column(4,
                               numericInput("shift18",label = NULL,value = 0))),
                    fluidRow(
                        column(4,
                               selectInput("weekday19",label = NULL,choices = list("Sunday" = 1, "Monday" = 2, "Tuesday" = 3,
                                                                                   "Wednesday" = 4, "Thursday" = 5, "Friday" = 6,
                                                                                   "Saturday" = 7),selected = 1)),
                        column(4,
                               selectInput("hour19",label = NULL,choices = list("0:00" = 1, "1:00" = 2, "2:00" = 3, "3:00" = 4,
                                                                                "4:00" = 5, "5:00" = 6, "6:00" = 7, "7:00" = 8,
                                                                                "8:00" = 9, "9:00" = 10, "10:00" = 11, "11:00" = 12,
                                                                                "12:00" = 13, "13:00" = 14, "14:00" = 15, "15:00" = 16,
                                                                                "16:00" = 17, "17:00" = 18, "18:00" = 19, "19:00" = 20,
                                                                                "20:00" = 21, "21:00" = 22, "22:00" = 23, "23:00" = 24),
                                           selected = 1)),
                        column(4,
                               numericInput("shift19",label = NULL,value = 0))),
                    fluidRow(
                        column(4,
                               selectInput("weekday20",label = NULL,choices = list("Sunday" = 1, "Monday" = 2, "Tuesday" = 3,
                                                                                   "Wednesday" = 4, "Thursday" = 5, "Friday" = 6,
                                                                                   "Saturday" = 7),selected = 1)),
                        column(4,
                               selectInput("hour20",label = NULL,choices = list("0:00" = 1, "1:00" = 2, "2:00" = 3, "3:00" = 4,
                                                                                "4:00" = 5, "5:00" = 6, "6:00" = 7, "7:00" = 8,
                                                                                "8:00" = 9, "9:00" = 10, "10:00" = 11, "11:00" = 12,
                                                                                "12:00" = 13, "13:00" = 14, "14:00" = 15, "15:00" = 16,
                                                                                "16:00" = 17, "17:00" = 18, "18:00" = 19, "19:00" = 20,
                                                                                "20:00" = 21, "21:00" = 22, "22:00" = 23, "23:00" = 24),
                                           selected = 1)),
                        column(4,
                               numericInput("shift20",label = NULL,value = 0))),
                    fluidRow(
                        column(4,
                               selectInput("weekday21",label = NULL,choices = list("Sunday" = 1, "Monday" = 2, "Tuesday" = 3,
                                                                                   "Wednesday" = 4, "Thursday" = 5, "Friday" = 6,
                                                                                   "Saturday" = 7),selected = 1)),
                        column(4,
                               selectInput("hour21",label = NULL,choices = list("0:00" = 1, "1:00" = 2, "2:00" = 3, "3:00" = 4,
                                                                                "4:00" = 5, "5:00" = 6, "6:00" = 7, "7:00" = 8,
                                                                                "8:00" = 9, "9:00" = 10, "10:00" = 11, "11:00" = 12,
                                                                                "12:00" = 13, "13:00" = 14, "14:00" = 15, "15:00" = 16,
                                                                                "16:00" = 17, "17:00" = 18, "18:00" = 19, "19:00" = 20,
                                                                                "20:00" = 21, "21:00" = 22, "22:00" = 23, "23:00" = 24),
                                           selected = 1)),
                        column(4,
                               numericInput("shift21",label = NULL,value = 0))),
                    fluidRow(
                        column(4,
                               selectInput("weekday22",label = NULL,choices = list("Sunday" = 1, "Monday" = 2, "Tuesday" = 3,
                                                                                   "Wednesday" = 4, "Thursday" = 5, "Friday" = 6,
                                                                                   "Saturday" = 7),selected = 1)),
                        column(4,
                               selectInput("hour22",label = NULL,choices = list("0:00" = 1, "1:00" = 2, "2:00" = 3, "3:00" = 4,
                                                                                "4:00" = 5, "5:00" = 6, "6:00" = 7, "7:00" = 8,
                                                                                "8:00" = 9, "9:00" = 10, "10:00" = 11, "11:00" = 12,
                                                                                "12:00" = 13, "13:00" = 14, "14:00" = 15, "15:00" = 16,
                                                                                "16:00" = 17, "17:00" = 18, "18:00" = 19, "19:00" = 20,
                                                                                "20:00" = 21, "21:00" = 22, "22:00" = 23, "23:00" = 24),
                                           selected = 1)),
                        column(4,
                               numericInput("shift22",label = NULL,value = 0))),
                    fluidRow(
                        column(4,
                               selectInput("weekday23",label = NULL,choices = list("Sunday" = 1, "Monday" = 2, "Tuesday" = 3,
                                                                                   "Wednesday" = 4, "Thursday" = 5, "Friday" = 6,
                                                                                   "Saturday" = 7),selected = 1)),
                        column(4,
                               selectInput("hour23",label = NULL,choices = list("0:00" = 1, "1:00" = 2, "2:00" = 3, "3:00" = 4,
                                                                                "4:00" = 5, "5:00" = 6, "6:00" = 7, "7:00" = 8,
                                                                                "8:00" = 9, "9:00" = 10, "10:00" = 11, "11:00" = 12,
                                                                                "12:00" = 13, "13:00" = 14, "14:00" = 15, "15:00" = 16,
                                                                                "16:00" = 17, "17:00" = 18, "18:00" = 19, "19:00" = 20,
                                                                                "20:00" = 21, "21:00" = 22, "22:00" = 23, "23:00" = 24),
                                           selected = 1)),
                        column(4,
                               numericInput("shift23",label = NULL,value = 0))),
                    fluidRow(
                        column(4,
                               selectInput("weekday24",label = NULL,choices = list("Sunday" = 1, "Monday" = 2, "Tuesday" = 3,
                                                                                   "Wednesday" = 4, "Thursday" = 5, "Friday" = 6,
                                                                                   "Saturday" = 7),selected = 1)),
                        column(4,
                               selectInput("hour24",label = NULL,choices = list("0:00" = 1, "1:00" = 2, "2:00" = 3, "3:00" = 4,
                                                                                "4:00" = 5, "5:00" = 6, "6:00" = 7, "7:00" = 8,
                                                                                "8:00" = 9, "9:00" = 10, "10:00" = 11, "11:00" = 12,
                                                                                "12:00" = 13, "13:00" = 14, "14:00" = 15, "15:00" = 16,
                                                                                "16:00" = 17, "17:00" = 18, "18:00" = 19, "19:00" = 20,
                                                                                "20:00" = 21, "21:00" = 22, "22:00" = 23, "23:00" = 24),
                                           selected = 1)),
                        column(4,
                               numericInput("shift24",label = NULL,value = 0))),
                    fluidRow(
                        column(4,
                               selectInput("weekday25",label = NULL,choices = list("Sunday" = 1, "Monday" = 2, "Tuesday" = 3,
                                                                                   "Wednesday" = 4, "Thursday" = 5, "Friday" = 6,
                                                                                   "Saturday" = 7),selected = 1)),
                        column(4,
                               selectInput("hour25",label = NULL,choices = list("0:00" = 1, "1:00" = 2, "2:00" = 3, "3:00" = 4,
                                                                                "4:00" = 5, "5:00" = 6, "6:00" = 7, "7:00" = 8,
                                                                                "8:00" = 9, "9:00" = 10, "10:00" = 11, "11:00" = 12,
                                                                                "12:00" = 13, "13:00" = 14, "14:00" = 15, "15:00" = 16,
                                                                                "16:00" = 17, "17:00" = 18, "18:00" = 19, "19:00" = 20,
                                                                                "20:00" = 21, "21:00" = 22, "22:00" = 23, "23:00" = 24),
                                           selected = 1)),
                        column(4,
                               numericInput("shift25",label = NULL,value = 0))),
                    fluidRow(
                        column(4,
                               selectInput("weekday26",label = NULL,choices = list("Sunday" = 1, "Monday" = 2, "Tuesday" = 3,
                                                                                   "Wednesday" = 4, "Thursday" = 5, "Friday" = 6,
                                                                                   "Saturday" = 7),selected = 1)),
                        column(4,
                               selectInput("hour26",label = NULL,choices = list("0:00" = 1, "1:00" = 2, "2:00" = 3, "3:00" = 4,
                                                                                "4:00" = 5, "5:00" = 6, "6:00" = 7, "7:00" = 8,
                                                                                "8:00" = 9, "9:00" = 10, "10:00" = 11, "11:00" = 12,
                                                                                "12:00" = 13, "13:00" = 14, "14:00" = 15, "15:00" = 16,
                                                                                "16:00" = 17, "17:00" = 18, "18:00" = 19, "19:00" = 20,
                                                                                "20:00" = 21, "21:00" = 22, "22:00" = 23, "23:00" = 24),
                                           selected = 1)),
                        column(4,
                               numericInput("shift26",label = NULL,value = 0))),
                    fluidRow(
                        column(4,
                               selectInput("weekday27",label = NULL,choices = list("Sunday" = 1, "Monday" = 2, "Tuesday" = 3,
                                                                                   "Wednesday" = 4, "Thursday" = 5, "Friday" = 6,
                                                                                   "Saturday" = 7),selected = 1)),
                        column(4,
                               selectInput("hour27",label = NULL,choices = list("0:00" = 1, "1:00" = 2, "2:00" = 3, "3:00" = 4,
                                                                                "4:00" = 5, "5:00" = 6, "6:00" = 7, "7:00" = 8,
                                                                                "8:00" = 9, "9:00" = 10, "10:00" = 11, "11:00" = 12,
                                                                                "12:00" = 13, "13:00" = 14, "14:00" = 15, "15:00" = 16,
                                                                                "16:00" = 17, "17:00" = 18, "18:00" = 19, "19:00" = 20,
                                                                                "20:00" = 21, "21:00" = 22, "22:00" = 23, "23:00" = 24),
                                           selected = 1)),
                        column(4,
                               numericInput("shift27",label = NULL,value = 0))),
                    fluidRow(
                        column(4,
                               selectInput("weekday28",label = NULL,choices = list("Sunday" = 1, "Monday" = 2, "Tuesday" = 3,
                                                                                   "Wednesday" = 4, "Thursday" = 5, "Friday" = 6,
                                                                                   "Saturday" = 7),selected = 1)),
                        column(4,
                               selectInput("hour28",label = NULL,choices = list("0:00" = 1, "1:00" = 2, "2:00" = 3, "3:00" = 4,
                                                                                "4:00" = 5, "5:00" = 6, "6:00" = 7, "7:00" = 8,
                                                                                "8:00" = 9, "9:00" = 10, "10:00" = 11, "11:00" = 12,
                                                                                "12:00" = 13, "13:00" = 14, "14:00" = 15, "15:00" = 16,
                                                                                "16:00" = 17, "17:00" = 18, "18:00" = 19, "19:00" = 20,
                                                                                "20:00" = 21, "21:00" = 22, "22:00" = 23, "23:00" = 24),
                                           selected = 1)),
                        column(4,
                               numericInput("shift28",label = NULL,value = 0))),
                    fluidRow(
                        column(4,
                               selectInput("weekday29",label = NULL,choices = list("Sunday" = 1, "Monday" = 2, "Tuesday" = 3,
                                                                                   "Wednesday" = 4, "Thursday" = 5, "Friday" = 6,
                                                                                   "Saturday" = 7),selected = 1)),
                        column(4,
                               selectInput("hour29",label = NULL,choices = list("0:00" = 1, "1:00" = 2, "2:00" = 3, "3:00" = 4,
                                                                                "4:00" = 5, "5:00" = 6, "6:00" = 7, "7:00" = 8,
                                                                                "8:00" = 9, "9:00" = 10, "10:00" = 11, "11:00" = 12,
                                                                                "12:00" = 13, "13:00" = 14, "14:00" = 15, "15:00" = 16,
                                                                                "16:00" = 17, "17:00" = 18, "18:00" = 19, "19:00" = 20,
                                                                                "20:00" = 21, "21:00" = 22, "22:00" = 23, "23:00" = 24),
                                           selected = 1)),
                        column(4,
                               numericInput("shift29",label = NULL,value = 0))),
                    fluidRow(
                        column(4,
                               selectInput("weekday30",label = NULL,choices = list("Sunday" = 1, "Monday" = 2, "Tuesday" = 3,
                                                                                   "Wednesday" = 4, "Thursday" = 5, "Friday" = 6,
                                                                                   "Saturday" = 7),selected = 1)),
                        column(4,
                               selectInput("hour30",label = NULL,choices = list("0:00" = 1, "1:00" = 2, "2:00" = 3, "3:00" = 4,
                                                                                "4:00" = 5, "5:00" = 6, "6:00" = 7, "7:00" = 8,
                                                                                "8:00" = 9, "9:00" = 10, "10:00" = 11, "11:00" = 12,
                                                                                "12:00" = 13, "13:00" = 14, "14:00" = 15, "15:00" = 16,
                                                                                "16:00" = 17, "17:00" = 18, "18:00" = 19, "19:00" = 20,
                                                                                "20:00" = 21, "21:00" = 22, "22:00" = 23, "23:00" = 24),
                                           selected = 1)),
                        column(4,
                               numericInput("shift30",label = NULL,value = 0)))
                ),
                mainPanel(
                   h1('Scheduled Capacity vs. Offered Load'),
                   
                   plotOutput("loadPlot"),
                   
                   textOutput("loadtext")

                )
            )
        )
)









